// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: api/fuelfinder/fuelfinder.proto

package fuelfinder

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FuelFinderClient is the client API for FuelFinder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FuelFinderClient interface {
	QueryArea(ctx context.Context, in *Geofence, opts ...grpc.CallOption) (*StationItems, error)
	Upload(ctx context.Context, in *StationItems, opts ...grpc.CallOption) (*UploadedItems, error)
	DistinctBrands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Brands, error)
}

type fuelFinderClient struct {
	cc grpc.ClientConnInterface
}

func NewFuelFinderClient(cc grpc.ClientConnInterface) FuelFinderClient {
	return &fuelFinderClient{cc}
}

func (c *fuelFinderClient) QueryArea(ctx context.Context, in *Geofence, opts ...grpc.CallOption) (*StationItems, error) {
	out := new(StationItems)
	err := c.cc.Invoke(ctx, "/fuelfinder.FuelFinder/QueryArea", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fuelFinderClient) Upload(ctx context.Context, in *StationItems, opts ...grpc.CallOption) (*UploadedItems, error) {
	out := new(UploadedItems)
	err := c.cc.Invoke(ctx, "/fuelfinder.FuelFinder/Upload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fuelFinderClient) DistinctBrands(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Brands, error) {
	out := new(Brands)
	err := c.cc.Invoke(ctx, "/fuelfinder.FuelFinder/DistinctBrands", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FuelFinderServer is the server API for FuelFinder service.
// All implementations must embed UnimplementedFuelFinderServer
// for forward compatibility
type FuelFinderServer interface {
	QueryArea(context.Context, *Geofence) (*StationItems, error)
	Upload(context.Context, *StationItems) (*UploadedItems, error)
	DistinctBrands(context.Context, *Empty) (*Brands, error)
	mustEmbedUnimplementedFuelFinderServer()
}

// UnimplementedFuelFinderServer must be embedded to have forward compatible implementations.
type UnimplementedFuelFinderServer struct {
}

func (UnimplementedFuelFinderServer) QueryArea(context.Context, *Geofence) (*StationItems, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryArea not implemented")
}
func (UnimplementedFuelFinderServer) Upload(context.Context, *StationItems) (*UploadedItems, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedFuelFinderServer) DistinctBrands(context.Context, *Empty) (*Brands, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DistinctBrands not implemented")
}
func (UnimplementedFuelFinderServer) mustEmbedUnimplementedFuelFinderServer() {}

// UnsafeFuelFinderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FuelFinderServer will
// result in compilation errors.
type UnsafeFuelFinderServer interface {
	mustEmbedUnimplementedFuelFinderServer()
}

func RegisterFuelFinderServer(s grpc.ServiceRegistrar, srv FuelFinderServer) {
	s.RegisterService(&FuelFinder_ServiceDesc, srv)
}

func _FuelFinder_QueryArea_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Geofence)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuelFinderServer).QueryArea(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelfinder.FuelFinder/QueryArea",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuelFinderServer).QueryArea(ctx, req.(*Geofence))
	}
	return interceptor(ctx, in, info, handler)
}

func _FuelFinder_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StationItems)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuelFinderServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelfinder.FuelFinder/Upload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuelFinderServer).Upload(ctx, req.(*StationItems))
	}
	return interceptor(ctx, in, info, handler)
}

func _FuelFinder_DistinctBrands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FuelFinderServer).DistinctBrands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fuelfinder.FuelFinder/DistinctBrands",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FuelFinderServer).DistinctBrands(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FuelFinder_ServiceDesc is the grpc.ServiceDesc for FuelFinder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FuelFinder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fuelfinder.FuelFinder",
	HandlerType: (*FuelFinderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryArea",
			Handler:    _FuelFinder_QueryArea_Handler,
		},
		{
			MethodName: "Upload",
			Handler:    _FuelFinder_Upload_Handler,
		},
		{
			MethodName: "DistinctBrands",
			Handler:    _FuelFinder_DistinctBrands_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/fuelfinder/fuelfinder.proto",
}
