name: Publish Docker Image CI

on:
  push:
    tags: ['*']

jobs:
  notify-start:
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack on build start
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: builds
          SLACK_COLOR: good # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
          SLACK_MESSAGE: 'The build is underway, you will be notified when it has finished :rocket:'
          SLACK_TITLE: Build Started for ${{ github.event.repository.name }} ${{ github.ref_name }}
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        
  build:
    runs-on: ubuntu-latest
    environment: Production
    strategy:
      matrix:
        include:
          - image: zakdamack/fuelfinder-frontend
            dockerfile: build/frontend.Dockerfile
          - image: zakdamack/fuelfinder-server
            dockerfile: build/server.Dockerfile
          - image: zakdamack/fuelfinder-scraper
            dockerfile: build/scraper.Dockerfile
          - image: zakdamack/fuelfinder-gateway
            dockerfile: build/gateway.Dockerfile
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ matrix.image }}
          tags: type=semver,pattern={{version}}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
  notify-end-state:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build]
    steps:   
      - uses: technote-space/workflow-conclusion-action@v3

      - name: Notify slack on build start
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: builds
          SLACK_COLOR: ${{ env.WORKFLOW_CONCLUSION }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png
          SLACK_MESSAGE: 'The workflow has finished and returned with ${{ env.WORKFLOW_CONCLUSION }} :rocket:'
          SLACK_TITLE: Build ${{ env.WORKFLOW_CONCLUSION }} for ${{ github.event.repository.name }} ${{ github.ref_name }}
          SLACK_USERNAME: GitHub Actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}